services:
  coturn:
    image: coturn/coturn:4.18.0-r0
    restart: unless-stopped
    network_mode: host
    command:
      - -n
      - --fingerprint
      - --log-file=stdout
      - --lt-cred-mech
      - --realm=${TURN_REALM}
      - --user=${TURN_USERNAME}:${TURN_CREDENTIAL}
      - --external-ip=${TURN_EXTERNAL_IP}
      - --tls-listening-port=443
      - --no-udp
      - --no-tcp
      - --no-stun
      - --min-port=49160
      - --max-port=49200
      - --no-multicast-peers
      - --no-tcp-relay
      - --denied-peer-ip=10.0.0.0-10.255.255.255
      - --denied-peer-ip=100.64.0.0-100.127.255.255
      - --denied-peer-ip=127.0.0.0-127.255.255.255
      - --denied-peer-ip=169.254.0.0-169.254.255.255
      - --denied-peer-ip=172.16.0.0-172.31.255.255
      - --denied-peer-ip=192.168.0.0-192.168.255.255
      - --user-quota=4
      - --total-quota=16
      - --cert=/certs/fullchain.pem
      - --pkey=/certs/privkey.pem
    volumes:
      - ${TURN_CERT_PATH}:/certs/fullchain.pem:ro
      - ${TURN_KEY_PATH}:/certs/privkey.pem:ro
